In [97]:
import pandas as pd

In [98]:
listbox = ["비빔밥", "김치찌게", "된장찌게"]

menu = pd.Series(listbox)
type(menu)

pandas.core.series.Series

In [99]:
listbox = [10000, 9000, 8000]

price = pd.Series(listbox)
price

0    10000
1     9000
2     8000
dtype: int64

In [100]:
dic = {
    "메뉴": menu, 
    "가격": price
}

df = pd.DataFrame(dic)
df

     메뉴     가격
0   비빔밥  10000
1  김치찌게   9000
2  된장찌게   8000

In [101]:
dic = {
    "메뉴": ["비빔밥", "김치찌게", "된장찌게"],
    "가격": [10000, 9000, 8000], 
    "원산지": ["국내산", "국내산", "국내산"]
}

df = pd.DataFrame(dic)
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌게   9000  국내산
2  된장찌게   8000  국내산

In [102]:
print(df[["메뉴"]])
print(df["가격"])

     메뉴
0   비빔밥
1  김치찌게
2  된장찌게
0    10000
1     9000
2     8000
Name: 가격, dtype: int64

In [103]:
df[["메뉴"]]

     메뉴
0   비빔밥
1  김치찌게
2  된장찌게

In [104]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌게   9000  국내산
2  된장찌게   8000  국내산

In [105]:
df[["메뉴", "가격"]]

     메뉴     가격
0   비빔밥  10000
1  김치찌게   9000
2  된장찌게   8000

In [106]:
type(df["메뉴"])

pandas.core.series.Series

In [107]:
type(df[["메뉴"]])

pandas.core.frame.DataFrame

In [108]:
dic = {
    "메뉴": ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격": [4500, 5000, 5500, 5000, 4000, 5900, 5300],
    "칼로리": [10, 110, 250, 110, 20, 210, 0]
}

df = pd.DataFrame(dic)
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [109]:
df.to_csv("temp.csv", encoding="cp949")

In [110]:
result = pd.read_csv("temp.csv", encoding="cp949")
result

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [111]:
# 03. 탐색적 데이터 분석(EDA)

df.head(2)
df.tail(1)
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [112]:
df.shape

(7, 3)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [114]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [115]:
data = {
    "car": ["Sedan", "SUV", "Sedan", "SUV", "SUV", "SUV", "Sedan", "Sedan", "Sedan", "Sedan", "Sedan"], 
    "size": ["S", "M", "S", "S", "M", "M", "L", "S", "S", "M", "S"]
}
df_car = pd.DataFrame(data)
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [116]:
df_car.nunique()

car     2
size    3
dtype: int64

In [117]:
## 고유한 값
print(df_car["car"].unique())
print(df_car["size"].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [118]:
## 고유한 값과 개수
print(df_car["car"].value_counts())
print(df_car["size"].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

In [119]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [120]:
## 기술통계 (숫자)
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [121]:
## 기술통계 (문자)
df.describe(include="O")

           메뉴
count       7
unique      7
top     아메리카노
freq        1

In [122]:
# 04. 자료형 변환

data = {
    "메뉴": ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격": [4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "칼로리": ['10', '110', '250', '110', '20', '210', '0']
}

df = pd.DataFrame(data)
df

      메뉴      가격  칼로리
0  아메리카노  4500.0   10
1   카페라떼  5000.0  110
2   카페모카  5500.0  250
3   카푸치노  5000.0  110
4  에스프레소  4000.0   20
5    밀크티  5900.0  210
6     녹차  5300.0    0

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [124]:
df["가격"] = df["가격"].astype("int")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [125]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [126]:
df["칼로리"] = df["칼로리"].astype("float")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [127]:
df.to_csv("cafe.csv", index=False)

In [128]:
df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [129]:
df["new"] = 0

In [130]:
df

      메뉴    가격    칼로리  new
0  아메리카노  4500   10.0    0
1   카페라떼  5000  110.0    0
2   카페모카  5500  250.0    0
3   카푸치노  5000  110.0    0
4  에스프레소  4000   20.0    0
5    밀크티  5900  210.0    0
6     녹차  5300    0.0    0

In [131]:
discount = 0.2

df["할인가"] = df["가격"] * (1 - discount)
df

      메뉴    가격    칼로리  new     할인가
0  아메리카노  4500   10.0    0  3600.0
1   카페라떼  5000  110.0    0  4000.0
2   카페모카  5500  250.0    0  4400.0
3   카푸치노  5000  110.0    0  4000.0
4  에스프레소  4000   20.0    0  3200.0
5    밀크티  5900  210.0    0  4720.0
6     녹차  5300    0.0    0  4240.0

In [132]:
# 06. 데이터 삭제

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [133]:
df.drop(1, axis=0, inplace=True)
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [134]:
df.drop("칼로리", axis=1, inplace=True)
df

      메뉴    가격
0  아메리카노  4500
2   카페모카  5500
3   카푸치노  5000
4  에스프레소  4000
5    밀크티  5900
6     녹차  5300

In [135]:
# 07. 인덱싱/슬라이싱(loc)

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [136]:
## 인덱싱
df.loc[1, "가격"]

np.int64(5000)

In [137]:
## 슬라이싱
df.loc[ : , "가격"]

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [138]:
df.loc[2, "메뉴":"가격"]

메뉴    카페모카
가격    5500
Name: 2, dtype: object

In [139]:
df.loc[1:3, "메뉴":"가격"]

     메뉴    가격
1  카페라떼  5000
2  카페모카  5500
3  카푸치노  5000

In [140]:
#08. 인덱싱/슬라이싱(iloc)

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [141]:
df.iloc[0]

메뉴     아메리카노
가격      4500
칼로리     10.0
Name: 0, dtype: object

In [142]:
df.iloc[:, 2]

0     10.0
1    110.0
2    250.0
3    110.0
4     20.0
5    210.0
6      0.0
Name: 칼로리, dtype: float64

In [143]:
df.iloc[2, 0:3]

메뉴      카페모카
가격      5500
칼로리    250.0
Name: 2, dtype: object

In [144]:
# 09. 데이터 추가/변경

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [146]:
## 결측치 대입
import numpy as np

df["원산지"] = np.nan
df

      메뉴    가격    칼로리  원산지
0  아메리카노  4500   10.0  NaN
1   카페라떼  5000  110.0  NaN
2   카페모카  5500  250.0  NaN
3   카푸치노  5000  110.0  NaN
4  에스프레소  4000   20.0  NaN
5    밀크티  5900  210.0  NaN
6     녹차  5300    0.0  NaN

In [148]:
## loc를 활용하여 값을 변경
df.loc[0, "원산지"] = "콜롬비아"
df

C:\Users\HRD영대\AppData\Local\Temp\ipykernel_9384\970864682.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0, "원산지"] = "콜롬비아"

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0   NaN
3   카푸치노  5000  110.0   NaN
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN

In [151]:
df.loc[2:3, "원산지"] = "과테말라"
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN

In [153]:
df.loc["시즌"] = ["크리스마스라떼", 6000, 300, "한국"]
df

         메뉴    가격    칼로리   원산지
0     아메리카노  4500   10.0  콜롬비아
1      카페라떼  5000  110.0   NaN
2      카페모카  5500  250.0  과테말라
3      카푸치노  5000  110.0  과테말라
4     에스프레소  4000   20.0   NaN
5       밀크티  5900  210.0   NaN
6        녹차  5300    0.0   NaN
시즌  크리스마스라떼  6000  300.0    한국

In [154]:
df.loc[7] = {
    "메뉴": "딴짓커피", 
    "가격": 2000, 
    "칼로리": 20
}
df

         메뉴    가격    칼로리   원산지
0     아메리카노  4500   10.0  콜롬비아
1      카페라떼  5000  110.0   NaN
2      카페모카  5500  250.0  과테말라
3      카푸치노  5000  110.0  과테말라
4     에스프레소  4000   20.0   NaN
5       밀크티  5900  210.0   NaN
6        녹차  5300    0.0   NaN
시즌  크리스마스라떼  6000  300.0    한국
7      딴짓커피  2000   20.0   NaN

In [155]:
df.drop("시즌", axis=0, inplace=True)
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [156]:
df.to_csv("cafe2.csv", index=False)