In [1]:
import pandas as pd

In [2]:
listbox = ["비빔밥", "김치찌게", "된장찌게"]

menu = pd.Series(listbox)
type(menu)

pandas.core.series.Series

In [3]:
listbox = [10000, 9000, 8000]

price = pd.Series(listbox)
price

0    10000
1     9000
2     8000
dtype: int64

In [4]:
dic = {
    "메뉴": menu, 
    "가격": price
}

df = pd.DataFrame(dic)
df

     메뉴     가격
0   비빔밥  10000
1  김치찌게   9000
2  된장찌게   8000

In [5]:
dic = {
    "메뉴": ["비빔밥", "김치찌게", "된장찌게"],
    "가격": [10000, 9000, 8000], 
    "원산지": ["국내산", "국내산", "국내산"]
}

df = pd.DataFrame(dic)
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌게   9000  국내산
2  된장찌게   8000  국내산

In [6]:
print(df[["메뉴"]])
print(df["가격"])

     메뉴
0   비빔밥
1  김치찌게
2  된장찌게
0    10000
1     9000
2     8000
Name: 가격, dtype: int64

In [7]:
df[["메뉴"]]

     메뉴
0   비빔밥
1  김치찌게
2  된장찌게

In [8]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌게   9000  국내산
2  된장찌게   8000  국내산

In [9]:
df[["메뉴", "가격"]]

     메뉴     가격
0   비빔밥  10000
1  김치찌게   9000
2  된장찌게   8000

In [10]:
type(df["메뉴"])

pandas.core.series.Series

In [11]:
type(df[["메뉴"]])

pandas.core.frame.DataFrame

In [12]:
dic = {
    "메뉴": ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격": [4500, 5000, 5500, 5000, 4000, 5900, 5300],
    "칼로리": [10, 110, 250, 110, 20, 210, 0]
}

df = pd.DataFrame(dic)
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [13]:
df.to_csv("temp.csv", encoding="cp949")

In [14]:
result = pd.read_csv("temp.csv", encoding="cp949")
result

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [15]:
# 03. 탐색적 데이터 분석(EDA)

df.head(2)
df.tail(1)
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [16]:
df.shape

(7, 3)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [18]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [19]:
data = {
    "car": ["Sedan", "SUV", "Sedan", "SUV", "SUV", "SUV", "Sedan", "Sedan", "Sedan", "Sedan", "Sedan"], 
    "size": ["S", "M", "S", "S", "M", "M", "L", "S", "S", "M", "S"]
}
df_car = pd.DataFrame(data)
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [20]:
df_car.nunique()

car     2
size    3
dtype: int64

In [21]:
## 고유한 값
print(df_car["car"].unique())
print(df_car["size"].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [22]:
## 고유한 값과 개수
print(df_car["car"].value_counts())
print(df_car["size"].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

In [23]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [24]:
## 기술통계 (숫자)
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [25]:
## 기술통계 (문자)
df.describe(include="O")

           메뉴
count       7
unique      7
top     아메리카노
freq        1

In [26]:
# 04. 자료형 변환

data = {
    "메뉴": ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격": [4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "칼로리": ['10', '110', '250', '110', '20', '210', '0']
}

df = pd.DataFrame(data)
df

      메뉴      가격  칼로리
0  아메리카노  4500.0   10
1   카페라떼  5000.0  110
2   카페모카  5500.0  250
3   카푸치노  5000.0  110
4  에스프레소  4000.0   20
5    밀크티  5900.0  210
6     녹차  5300.0    0

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [28]:
df["가격"] = df["가격"].astype("int")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [29]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [30]:
df["칼로리"] = df["칼로리"].astype("float")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [31]:
df.to_csv("cafe.csv", index=False)

In [32]:
df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [33]:
df["new"] = 0

In [34]:
df

      메뉴    가격    칼로리  new
0  아메리카노  4500   10.0    0
1   카페라떼  5000  110.0    0
2   카페모카  5500  250.0    0
3   카푸치노  5000  110.0    0
4  에스프레소  4000   20.0    0
5    밀크티  5900  210.0    0
6     녹차  5300    0.0    0

In [35]:
discount = 0.2

df["할인가"] = df["가격"] * (1 - discount)
df

      메뉴    가격    칼로리  new     할인가
0  아메리카노  4500   10.0    0  3600.0
1   카페라떼  5000  110.0    0  4000.0
2   카페모카  5500  250.0    0  4400.0
3   카푸치노  5000  110.0    0  4000.0
4  에스프레소  4000   20.0    0  3200.0
5    밀크티  5900  210.0    0  4720.0
6     녹차  5300    0.0    0  4240.0

In [36]:
# 06. 데이터 삭제

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [37]:
df.drop(1, axis=0, inplace=True)
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [38]:
df.drop("칼로리", axis=1, inplace=True)
df

      메뉴    가격
0  아메리카노  4500
2   카페모카  5500
3   카푸치노  5000
4  에스프레소  4000
5    밀크티  5900
6     녹차  5300

In [39]:
# 07. 인덱싱/슬라이싱(loc)

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [40]:
## 인덱싱
df.loc[1, "가격"]

np.int64(5000)

In [41]:
## 슬라이싱
df.loc[ : , "가격"]

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [42]:
df.loc[2, "메뉴":"가격"]

메뉴    카페모카
가격    5500
Name: 2, dtype: object

In [43]:
df.loc[1:3, "메뉴":"가격"]

     메뉴    가격
1  카페라떼  5000
2  카페모카  5500
3  카푸치노  5000

In [44]:
#08. 인덱싱/슬라이싱(iloc)

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [45]:
df.iloc[0]

메뉴     아메리카노
가격      4500
칼로리     10.0
Name: 0, dtype: object

In [46]:
df.iloc[:, 2]

0     10.0
1    110.0
2    250.0
3    110.0
4     20.0
5    210.0
6      0.0
Name: 칼로리, dtype: float64

In [47]:
df.iloc[2, 0:3]

메뉴      카페모카
가격      5500
칼로리    250.0
Name: 2, dtype: object

In [48]:
# 09. 데이터 추가/변경

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [49]:
## 결측치 대입
import numpy as np

df["원산지"] = np.nan
df

      메뉴    가격    칼로리  원산지
0  아메리카노  4500   10.0  NaN
1   카페라떼  5000  110.0  NaN
2   카페모카  5500  250.0  NaN
3   카푸치노  5000  110.0  NaN
4  에스프레소  4000   20.0  NaN
5    밀크티  5900  210.0  NaN
6     녹차  5300    0.0  NaN

In [50]:
## loc를 활용하여 값을 변경
df.loc[0, "원산지"] = "콜롬비아"
df

C:\Users\HRD영대\AppData\Local\Temp\ipykernel_6892\970864682.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0, "원산지"] = "콜롬비아"

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0   NaN
3   카푸치노  5000  110.0   NaN
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN

In [51]:
df.loc[2:3, "원산지"] = "과테말라"
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN

In [52]:
df.loc["시즌"] = ["크리스마스라떼", 6000, 300, "한국"]
df

         메뉴    가격    칼로리   원산지
0     아메리카노  4500   10.0  콜롬비아
1      카페라떼  5000  110.0   NaN
2      카페모카  5500  250.0  과테말라
3      카푸치노  5000  110.0  과테말라
4     에스프레소  4000   20.0   NaN
5       밀크티  5900  210.0   NaN
6        녹차  5300    0.0   NaN
시즌  크리스마스라떼  6000  300.0    한국

In [53]:
df.loc[7] = {
    "메뉴": "딴짓커피", 
    "가격": 2000, 
    "칼로리": 20
}
df

         메뉴    가격    칼로리   원산지
0     아메리카노  4500   10.0  콜롬비아
1      카페라떼  5000  110.0   NaN
2      카페모카  5500  250.0  과테말라
3      카푸치노  5000  110.0  과테말라
4     에스프레소  4000   20.0   NaN
5       밀크티  5900  210.0   NaN
6        녹차  5300    0.0   NaN
시즌  크리스마스라떼  6000  300.0    한국
7      딴짓커피  2000   20.0   NaN

In [54]:
df.drop("시즌", axis=0, inplace=True)
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [55]:
df.to_csv("cafe2.csv", index=False)

In [56]:
# 10. 정렬

df = pd.read_csv("cafe2.csv")
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [57]:
df.sort_index(ascending=False)

      메뉴    가격    칼로리   원산지
7   딴짓커피  2000   20.0   NaN
6     녹차  5300    0.0   NaN
5    밀크티  5900  210.0   NaN
4  에스프레소  4000   20.0   NaN
3   카푸치노  5000  110.0  과테말라
2   카페모카  5500  250.0  과테말라
1   카페라떼  5000  110.0   NaN
0  아메리카노  4500   10.0  콜롬비아

In [58]:
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [59]:
df.sort_values("메뉴")

      메뉴    가격    칼로리   원산지
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN
5    밀크티  5900  210.0   NaN
0  아메리카노  4500   10.0  콜롬비아
4  에스프레소  4000   20.0   NaN
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라

In [60]:
df.sort_values("메뉴", ascending=False)

      메뉴    가격    칼로리   원산지
3   카푸치노  5000  110.0  과테말라
2   카페모카  5500  250.0  과테말라
1   카페라떼  5000  110.0   NaN
4  에스프레소  4000   20.0   NaN
0  아메리카노  4500   10.0  콜롬비아
5    밀크티  5900  210.0   NaN
7   딴짓커피  2000   20.0   NaN
6     녹차  5300    0.0   NaN

In [61]:
df.sort_values("칼로리")

      메뉴    가격    칼로리   원산지
6     녹차  5300    0.0   NaN
0  아메리카노  4500   10.0  콜롬비아
4  에스프레소  4000   20.0   NaN
7   딴짓커피  2000   20.0   NaN
1   카페라떼  5000  110.0   NaN
3   카푸치노  5000  110.0  과테말라
5    밀크티  5900  210.0   NaN
2   카페모카  5500  250.0  과테말라

In [62]:
## 2개 이상의 기준 정렬

df = df.sort_index()
df

df.sort_values(["가격", "메뉴"], ascending=[False, True], inplace=True)
df

      메뉴    가격    칼로리   원산지
5    밀크티  5900  210.0   NaN
2   카페모카  5500  250.0  과테말라
6     녹차  5300    0.0   NaN
1   카페라떼  5000  110.0   NaN
3   카푸치노  5000  110.0  과테말라
0  아메리카노  4500   10.0  콜롬비아
4  에스프레소  4000   20.0   NaN
7   딴짓커피  2000   20.0   NaN

In [63]:
df.reset_index(drop=True)

      메뉴    가격    칼로리   원산지
0    밀크티  5900  210.0   NaN
1   카페모카  5500  250.0  과테말라
2     녹차  5300    0.0   NaN
3   카페라떼  5000  110.0   NaN
4   카푸치노  5000  110.0  과테말라
5  아메리카노  4500   10.0  콜롬비아
6  에스프레소  4000   20.0   NaN
7   딴짓커피  2000   20.0   NaN

In [64]:
# 11. 필터링

df = pd.read_csv("./cafe2.csv")
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [65]:
df["칼로리"] < 50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7     True
Name: 칼로리, dtype: bool

In [67]:
df[df["칼로리"] < 50]

      메뉴    가격   칼로리   원산지
0  아메리카노  4500  10.0  콜롬비아
4  에스프레소  4000  20.0   NaN
6     녹차  5300   0.0   NaN
7   딴짓커피  2000  20.0   NaN

In [68]:
cond = df["칼로리"] < 50
df[cond]

      메뉴    가격   칼로리   원산지
0  아메리카노  4500  10.0  콜롬비아
4  에스프레소  4000  20.0   NaN
6     녹차  5300   0.0   NaN
7   딴짓커피  2000  20.0   NaN

In [69]:
cond = df["칼로리"] < 50
df[~cond]

     메뉴    가격    칼로리   원산지
1  카페라떼  5000  110.0   NaN
2  카페모카  5500  250.0  과테말라
3  카푸치노  5000  110.0  과테말라
5   밀크티  5900  210.0   NaN

In [74]:
~(df["칼로리"] < 50)

0    False
1     True
2     True
3     True
4    False
5     True
6    False
7    False
Name: 칼로리, dtype: bool

In [77]:
# and : &
# or : | 
df

cond1 = (df["가격"] > 5000)
cond2 = (df["칼로리"] > 100)
df[cond1 & cond2]
df[cond1 | cond2]

     메뉴    가격    칼로리   원산지
1  카페라떼  5000  110.0   NaN
2  카페모카  5500  250.0  과테말라
3  카푸치노  5000  110.0  과테말라
5   밀크티  5900  210.0   NaN
6    녹차  5300    0.0   NaN

In [78]:
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [80]:
cond = (df["원산지"] == "과테말라")

df[cond]

     메뉴    가격    칼로리   원산지
2  카페모카  5500  250.0  과테말라
3  카푸치노  5000  110.0  과테말라

In [83]:
cond1 = df["원산지"] == "과테말라"
cond2 = df["가격"] <= 5000
df[(df["원산지"] == "과테말라") & (df["가격"] <= 5000)]

     메뉴    가격    칼로리   원산지
3  카푸치노  5000  110.0  과테말라

In [86]:
## isin()

cond = df["메뉴"].isin(["녹차"])
df[cond]

   메뉴    가격  칼로리  원산지
6  녹차  5300  0.0  NaN

In [90]:
cond = df["메뉴"].isin(["녹차", "카푸치노", "카페라떼"])
df[cond]

     메뉴    가격    칼로리   원산지
1  카페라떼  5000  110.0   NaN
3  카푸치노  5000  110.0  과테말라
6    녹차  5300    0.0   NaN

In [91]:
# 12. 결측치 처리

df = pd.read_csv("cafe2.csv")
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [ ]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [ ]:
## 결측값 구하기
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [95]:
df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [104]:
df = pd.read_csv("cafe2.csv")
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [ ]:
## 결측치 채우기 1
df
df["원산지"] = df["원산지"].fillna("코스타리카")
df

      메뉴    가격    칼로리    원산지
0  아메리카노  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6     녹차  5300    0.0  코스타리카
7   딴짓커피  2000   20.0  코스타리카

In [105]:
## 결측치 채우기 2

df["원산지"].fillna("코스타리카", inplace=True)
df

      메뉴    가격    칼로리    원산지
0  아메리카노  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6     녹차  5300    0.0  코스타리카
7   딴짓커피  2000   20.0  코스타리카