In [1]:
import pandas as pd

In [2]:
listbox = ["비빔밥", "김치찌게", "된장찌게"]

menu = pd.Series(listbox)
type(menu)

pandas.core.series.Series

In [3]:
listbox = [10000, 9000, 8000]

price = pd.Series(listbox)
price

0    10000
1     9000
2     8000
dtype: int64

In [4]:
dic = {
    "메뉴": menu, 
    "가격": price
}

df = pd.DataFrame(dic)
df

     메뉴     가격
0   비빔밥  10000
1  김치찌게   9000
2  된장찌게   8000

In [5]:
dic = {
    "메뉴": ["비빔밥", "김치찌게", "된장찌게"],
    "가격": [10000, 9000, 8000], 
    "원산지": ["국내산", "국내산", "국내산"]
}

df = pd.DataFrame(dic)
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌게   9000  국내산
2  된장찌게   8000  국내산

In [6]:
print(df[["메뉴"]])
print(df["가격"])

     메뉴
0   비빔밥
1  김치찌게
2  된장찌게
0    10000
1     9000
2     8000
Name: 가격, dtype: int64

In [7]:
df[["메뉴"]]

     메뉴
0   비빔밥
1  김치찌게
2  된장찌게

In [8]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌게   9000  국내산
2  된장찌게   8000  국내산

In [9]:
df[["메뉴", "가격"]]

     메뉴     가격
0   비빔밥  10000
1  김치찌게   9000
2  된장찌게   8000

In [10]:
type(df["메뉴"])

pandas.core.series.Series

In [11]:
type(df[["메뉴"]])

pandas.core.frame.DataFrame

In [12]:
dic = {
    "메뉴": ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격": [4500, 5000, 5500, 5000, 4000, 5900, 5300],
    "칼로리": [10, 110, 250, 110, 20, 210, 0]
}

df = pd.DataFrame(dic)
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [13]:
df.to_csv("temp.csv", encoding="cp949")

In [14]:
result = pd.read_csv("temp.csv", encoding="cp949")
result

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [ ]:
# 03. 탐색적 데이터 분석(EDA)

df.head(2)
df.tail(1)
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [26]:
df.shape

(7, 3)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [ ]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000