In [221]:
import pandas as pd

In [222]:
listbox = ["비빔밥", "김치찌게", "된장찌게"]

menu = pd.Series(listbox)
type(menu)

pandas.core.series.Series

In [223]:
listbox = [10000, 9000, 8000]

price = pd.Series(listbox)
price

0    10000
1     9000
2     8000
dtype: int64

In [224]:
dic = {
    "메뉴": menu, 
    "가격": price
}

df = pd.DataFrame(dic)
df

     메뉴     가격
0   비빔밥  10000
1  김치찌게   9000
2  된장찌게   8000

In [225]:
dic = {
    "메뉴": ["비빔밥", "김치찌게", "된장찌게"],
    "가격": [10000, 9000, 8000], 
    "원산지": ["국내산", "국내산", "국내산"]
}

df = pd.DataFrame(dic)
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌게   9000  국내산
2  된장찌게   8000  국내산

In [226]:
print(df[["메뉴"]])
print(df["가격"])

     메뉴
0   비빔밥
1  김치찌게
2  된장찌게
0    10000
1     9000
2     8000
Name: 가격, dtype: int64

In [227]:
df[["메뉴"]]

     메뉴
0   비빔밥
1  김치찌게
2  된장찌게

In [228]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌게   9000  국내산
2  된장찌게   8000  국내산

In [229]:
df[["메뉴", "가격"]]

     메뉴     가격
0   비빔밥  10000
1  김치찌게   9000
2  된장찌게   8000

In [230]:
type(df["메뉴"])

pandas.core.series.Series

In [231]:
type(df[["메뉴"]])

pandas.core.frame.DataFrame

In [232]:
dic = {
    "메뉴": ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격": [4500, 5000, 5500, 5000, 4000, 5900, 5300],
    "칼로리": [10, 110, 250, 110, 20, 210, 0]
}

df = pd.DataFrame(dic)
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [233]:
df.to_csv("temp.csv", encoding="cp949")

In [234]:
result = pd.read_csv("temp.csv", encoding="cp949")
result

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [235]:
# 03. 탐색적 데이터 분석(EDA)

df.head(2)
df.tail(1)
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [236]:
df.shape

(7, 3)

In [237]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [238]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [239]:
data = {
    "car": ["Sedan", "SUV", "Sedan", "SUV", "SUV", "SUV", "Sedan", "Sedan", "Sedan", "Sedan", "Sedan"], 
    "size": ["S", "M", "S", "S", "M", "M", "L", "S", "S", "M", "S"]
}
df_car = pd.DataFrame(data)
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [240]:
df_car.nunique()

car     2
size    3
dtype: int64

In [241]:
## 고유한 값
print(df_car["car"].unique())
print(df_car["size"].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [242]:
## 고유한 값과 개수
print(df_car["car"].value_counts())
print(df_car["size"].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

In [243]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [244]:
## 기술통계 (숫자)
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [245]:
## 기술통계 (문자)
df.describe(include="O")

           메뉴
count       7
unique      7
top     아메리카노
freq        1

In [246]:
# 04. 자료형 변환

data = {
    "메뉴": ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격": [4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "칼로리": ['10', '110', '250', '110', '20', '210', '0']
}

df = pd.DataFrame(data)
df

      메뉴      가격  칼로리
0  아메리카노  4500.0   10
1   카페라떼  5000.0  110
2   카페모카  5500.0  250
3   카푸치노  5000.0  110
4  에스프레소  4000.0   20
5    밀크티  5900.0  210
6     녹차  5300.0    0

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [248]:
df["가격"] = df["가격"].astype("int")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [249]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [250]:
df["칼로리"] = df["칼로리"].astype("float")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [251]:
df.to_csv("cafe.csv", index=False)

In [252]:
df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [253]:
df["new"] = 0

In [254]:
df

      메뉴    가격    칼로리  new
0  아메리카노  4500   10.0    0
1   카페라떼  5000  110.0    0
2   카페모카  5500  250.0    0
3   카푸치노  5000  110.0    0
4  에스프레소  4000   20.0    0
5    밀크티  5900  210.0    0
6     녹차  5300    0.0    0

In [255]:
discount = 0.2

df["할인가"] = df["가격"] * (1 - discount)
df

      메뉴    가격    칼로리  new     할인가
0  아메리카노  4500   10.0    0  3600.0
1   카페라떼  5000  110.0    0  4000.0
2   카페모카  5500  250.0    0  4400.0
3   카푸치노  5000  110.0    0  4000.0
4  에스프레소  4000   20.0    0  3200.0
5    밀크티  5900  210.0    0  4720.0
6     녹차  5300    0.0    0  4240.0

In [256]:
# 06. 데이터 삭제

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [257]:
df.drop(1, axis=0, inplace=True)
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [258]:
df.drop("칼로리", axis=1, inplace=True)
df

      메뉴    가격
0  아메리카노  4500
2   카페모카  5500
3   카푸치노  5000
4  에스프레소  4000
5    밀크티  5900
6     녹차  5300

In [259]:
# 07. 인덱싱/슬라이싱(loc)

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [260]:
## 인덱싱
df.loc[1, "가격"]

np.int64(5000)

In [261]:
## 슬라이싱
df.loc[ : , "가격"]

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [262]:
df.loc[2, "메뉴":"가격"]

메뉴    카페모카
가격    5500
Name: 2, dtype: object

In [263]:
df.loc[1:3, "메뉴":"가격"]

     메뉴    가격
1  카페라떼  5000
2  카페모카  5500
3  카푸치노  5000

In [264]:
#08. 인덱싱/슬라이싱(iloc)

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [265]:
df.iloc[0]

메뉴     아메리카노
가격      4500
칼로리     10.0
Name: 0, dtype: object

In [266]:
df.iloc[:, 2]

0     10.0
1    110.0
2    250.0
3    110.0
4     20.0
5    210.0
6      0.0
Name: 칼로리, dtype: float64

In [267]:
df.iloc[2, 0:3]

메뉴      카페모카
가격      5500
칼로리    250.0
Name: 2, dtype: object

In [268]:
# 09. 데이터 추가/변경

df = pd.read_csv("cafe.csv")
df

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0
5    밀크티  5900  210.0
6     녹차  5300    0.0

In [269]:
## 결측치 대입
import numpy as np

df["원산지"] = np.nan
df

      메뉴    가격    칼로리  원산지
0  아메리카노  4500   10.0  NaN
1   카페라떼  5000  110.0  NaN
2   카페모카  5500  250.0  NaN
3   카푸치노  5000  110.0  NaN
4  에스프레소  4000   20.0  NaN
5    밀크티  5900  210.0  NaN
6     녹차  5300    0.0  NaN

In [270]:
## loc를 활용하여 값을 변경
df.loc[0, "원산지"] = "콜롬비아"
df

C:\Users\HRD영대\AppData\Local\Temp\ipykernel_6892\970864682.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0, "원산지"] = "콜롬비아"

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0   NaN
3   카푸치노  5000  110.0   NaN
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN

In [271]:
df.loc[2:3, "원산지"] = "과테말라"
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN

In [272]:
df.loc["시즌"] = ["크리스마스라떼", 6000, 300, "한국"]
df

         메뉴    가격    칼로리   원산지
0     아메리카노  4500   10.0  콜롬비아
1      카페라떼  5000  110.0   NaN
2      카페모카  5500  250.0  과테말라
3      카푸치노  5000  110.0  과테말라
4     에스프레소  4000   20.0   NaN
5       밀크티  5900  210.0   NaN
6        녹차  5300    0.0   NaN
시즌  크리스마스라떼  6000  300.0    한국

In [273]:
df.loc[7] = {
    "메뉴": "딴짓커피", 
    "가격": 2000, 
    "칼로리": 20
}
df

         메뉴    가격    칼로리   원산지
0     아메리카노  4500   10.0  콜롬비아
1      카페라떼  5000  110.0   NaN
2      카페모카  5500  250.0  과테말라
3      카푸치노  5000  110.0  과테말라
4     에스프레소  4000   20.0   NaN
5       밀크티  5900  210.0   NaN
6        녹차  5300    0.0   NaN
시즌  크리스마스라떼  6000  300.0    한국
7      딴짓커피  2000   20.0   NaN

In [274]:
df.drop("시즌", axis=0, inplace=True)
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [275]:
df.to_csv("cafe2.csv", index=False)

In [276]:
# 10. 정렬

df = pd.read_csv("cafe2.csv")
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [277]:
df.sort_index(ascending=False)

      메뉴    가격    칼로리   원산지
7   딴짓커피  2000   20.0   NaN
6     녹차  5300    0.0   NaN
5    밀크티  5900  210.0   NaN
4  에스프레소  4000   20.0   NaN
3   카푸치노  5000  110.0  과테말라
2   카페모카  5500  250.0  과테말라
1   카페라떼  5000  110.0   NaN
0  아메리카노  4500   10.0  콜롬비아

In [278]:
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [279]:
df.sort_values("메뉴")

      메뉴    가격    칼로리   원산지
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN
5    밀크티  5900  210.0   NaN
0  아메리카노  4500   10.0  콜롬비아
4  에스프레소  4000   20.0   NaN
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라

In [280]:
df.sort_values("메뉴", ascending=False)

      메뉴    가격    칼로리   원산지
3   카푸치노  5000  110.0  과테말라
2   카페모카  5500  250.0  과테말라
1   카페라떼  5000  110.0   NaN
4  에스프레소  4000   20.0   NaN
0  아메리카노  4500   10.0  콜롬비아
5    밀크티  5900  210.0   NaN
7   딴짓커피  2000   20.0   NaN
6     녹차  5300    0.0   NaN

In [281]:
df.sort_values("칼로리")

      메뉴    가격    칼로리   원산지
6     녹차  5300    0.0   NaN
0  아메리카노  4500   10.0  콜롬비아
4  에스프레소  4000   20.0   NaN
7   딴짓커피  2000   20.0   NaN
1   카페라떼  5000  110.0   NaN
3   카푸치노  5000  110.0  과테말라
5    밀크티  5900  210.0   NaN
2   카페모카  5500  250.0  과테말라

In [282]:
## 2개 이상의 기준 정렬

df = df.sort_index()
df

df.sort_values(["가격", "메뉴"], ascending=[False, True], inplace=True)
df

      메뉴    가격    칼로리   원산지
5    밀크티  5900  210.0   NaN
2   카페모카  5500  250.0  과테말라
6     녹차  5300    0.0   NaN
1   카페라떼  5000  110.0   NaN
3   카푸치노  5000  110.0  과테말라
0  아메리카노  4500   10.0  콜롬비아
4  에스프레소  4000   20.0   NaN
7   딴짓커피  2000   20.0   NaN

In [283]:
df.reset_index(drop=True)

      메뉴    가격    칼로리   원산지
0    밀크티  5900  210.0   NaN
1   카페모카  5500  250.0  과테말라
2     녹차  5300    0.0   NaN
3   카페라떼  5000  110.0   NaN
4   카푸치노  5000  110.0  과테말라
5  아메리카노  4500   10.0  콜롬비아
6  에스프레소  4000   20.0   NaN
7   딴짓커피  2000   20.0   NaN

In [284]:
# 11. 필터링

df = pd.read_csv("./cafe2.csv")
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [285]:
df["칼로리"] < 50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7     True
Name: 칼로리, dtype: bool

In [286]:
df[df["칼로리"] < 50]

      메뉴    가격   칼로리   원산지
0  아메리카노  4500  10.0  콜롬비아
4  에스프레소  4000  20.0   NaN
6     녹차  5300   0.0   NaN
7   딴짓커피  2000  20.0   NaN

In [287]:
cond = df["칼로리"] < 50
df[cond]

      메뉴    가격   칼로리   원산지
0  아메리카노  4500  10.0  콜롬비아
4  에스프레소  4000  20.0   NaN
6     녹차  5300   0.0   NaN
7   딴짓커피  2000  20.0   NaN

In [288]:
cond = df["칼로리"] < 50
df[~cond]

     메뉴    가격    칼로리   원산지
1  카페라떼  5000  110.0   NaN
2  카페모카  5500  250.0  과테말라
3  카푸치노  5000  110.0  과테말라
5   밀크티  5900  210.0   NaN

In [289]:
~(df["칼로리"] < 50)

0    False
1     True
2     True
3     True
4    False
5     True
6    False
7    False
Name: 칼로리, dtype: bool

In [290]:
# and : &
# or : | 
df

cond1 = (df["가격"] > 5000)
cond2 = (df["칼로리"] > 100)
df[cond1 & cond2]
df[cond1 | cond2]

     메뉴    가격    칼로리   원산지
1  카페라떼  5000  110.0   NaN
2  카페모카  5500  250.0  과테말라
3  카푸치노  5000  110.0  과테말라
5   밀크티  5900  210.0   NaN
6    녹차  5300    0.0   NaN

In [291]:
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [292]:
cond = (df["원산지"] == "과테말라")

df[cond]

     메뉴    가격    칼로리   원산지
2  카페모카  5500  250.0  과테말라
3  카푸치노  5000  110.0  과테말라

In [293]:
cond1 = df["원산지"] == "과테말라"
cond2 = df["가격"] <= 5000
df[(df["원산지"] == "과테말라") & (df["가격"] <= 5000)]

     메뉴    가격    칼로리   원산지
3  카푸치노  5000  110.0  과테말라

In [294]:
## isin()

cond = df["메뉴"].isin(["녹차"])
df[cond]

   메뉴    가격  칼로리  원산지
6  녹차  5300  0.0  NaN

In [295]:
cond = df["메뉴"].isin(["녹차", "카푸치노", "카페라떼"])
df[cond]

     메뉴    가격    칼로리   원산지
1  카페라떼  5000  110.0   NaN
3  카푸치노  5000  110.0  과테말라
6    녹차  5300    0.0   NaN

In [296]:
# 12. 결측치 처리

df = pd.read_csv("cafe2.csv")
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [297]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [298]:
## 결측값 구하기
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [299]:
df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [300]:
df = pd.read_csv("cafe2.csv")
df

      메뉴    가격    칼로리   원산지
0  아메리카노  4500   10.0  콜롬비아
1   카페라떼  5000  110.0   NaN
2   카페모카  5500  250.0  과테말라
3   카푸치노  5000  110.0  과테말라
4  에스프레소  4000   20.0   NaN
5    밀크티  5900  210.0   NaN
6     녹차  5300    0.0   NaN
7   딴짓커피  2000   20.0   NaN

In [301]:
## 결측치 채우기 1
df
df["원산지"] = df["원산지"].fillna("코스타리카")
df

      메뉴    가격    칼로리    원산지
0  아메리카노  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6     녹차  5300    0.0  코스타리카
7   딴짓커피  2000   20.0  코스타리카

In [302]:
## 결측치 채우기 2

df["원산지"].fillna("코스타리카", inplace=True)
df

C:\Users\HRD영대\AppData\Local\Temp\ipykernel_6892\1112097746.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["원산지"].fillna("코스타리카", inplace=True)

      메뉴    가격    칼로리    원산지
0  아메리카노  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6     녹차  5300    0.0  코스타리카
7   딴짓커피  2000   20.0  코스타리카

In [303]:
df

      메뉴    가격    칼로리    원산지
0  아메리카노  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6     녹차  5300    0.0  코스타리카
7   딴짓커피  2000   20.0  코스타리카

In [304]:
df.to_csv("cafe3.csv", index=False)

In [305]:
# 13. 값 변경

df = pd.read_csv("cafe3.csv")
df

      메뉴    가격    칼로리    원산지
0  아메리카노  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6     녹차  5300    0.0  코스타리카
7   딴짓커피  2000   20.0  코스타리카

In [306]:
df.replace("아메리카노", "롱고", inplace=True)
df

      메뉴    가격    칼로리    원산지
0     롱고  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6     녹차  5300    0.0  코스타리카
7   딴짓커피  2000   20.0  코스타리카

In [307]:
df.replace("녹차", "그린티", inplace=True)
df

      메뉴    가격    칼로리    원산지
0     롱고  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6    그린티  5300    0.0  코스타리카
7   딴짓커피  2000   20.0  코스타리카

In [308]:
df.replace({
    "롱고":"아메리카노", 
    "그린티": "녹차"}, inplace=True)
df

      메뉴    가격    칼로리    원산지
0  아메리카노  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6     녹차  5300    0.0  코스타리카
7   딴짓커피  2000   20.0  코스타리카

In [309]:
df.loc[6, "원산지"] = "대한민국"
df

      메뉴    가격    칼로리    원산지
0  아메리카노  4500   10.0   콜롬비아
1   카페라떼  5000  110.0  코스타리카
2   카페모카  5500  250.0   과테말라
3   카푸치노  5000  110.0   과테말라
4  에스프레소  4000   20.0  코스타리카
5    밀크티  5900  210.0  코스타리카
6     녹차  5300    0.0   대한민국
7   딴짓커피  2000   20.0  코스타리카

In [310]:
df.loc[1:2, "이벤트가"] = 1000
df

      메뉴    가격    칼로리    원산지    이벤트가
0  아메리카노  4500   10.0   콜롬비아     NaN
1   카페라떼  5000  110.0  코스타리카  1000.0
2   카페모카  5500  250.0   과테말라  1000.0
3   카푸치노  5000  110.0   과테말라     NaN
4  에스프레소  4000   20.0  코스타리카     NaN
5    밀크티  5900  210.0  코스타리카     NaN
6     녹차  5300    0.0   대한민국     NaN
7   딴짓커피  2000   20.0  코스타리카     NaN

In [311]:
df.to_csv("cafe4.csv", index=False)

In [312]:
# 14. 문자열
data = {
    "A": ["데이터 분석", "기본 학습서", "퇴근 후 열공"], 
    "B": [10, 20, 30], 
    "C": ["ab cd", "AB CD", "ab cd"]
}

df = pd.DataFrame(data)
df

         A   B      C
0   데이터 분석  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [313]:
df["A"] = df["A"].replace("분석", "시각화")
df

         A   B      C
0   데이터 분석  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [314]:
df["A"] = df["A"].str.replace("분석", "시각화")
df

         A   B      C
0  데이터 시각화  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [315]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      object
 1   B       3 non-null      int64
 2   C       3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [316]:
df["B"].str.replace(10, 100)

AttributeError: Can only use .str accessor with string values!

In [ ]:
## 문자열 분리
df["A"].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [ ]:
df["A"].str.split()[2]

['퇴근', '후', '열공']

In [ ]:
df

         A   B      C
0  데이터 시각화  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [317]:
df["A"] = df["A"].str.split().str[0]
df

     A   B      C
0  데이터  10  ab cd
1   기본  20  AB CD
2   퇴근  30  ab cd

In [318]:
## 특정 문자열 검색
df

     A   B      C
0  데이터  10  ab cd
1   기본  20  AB CD
2   퇴근  30  ab cd

In [320]:
df[df["A"].str.contains("기본")]

    A   B      C
1  기본  20  AB CD

In [321]:
## 문자열 길이
df

     A   B      C
0  데이터  10  ab cd
1   기본  20  AB CD
2   퇴근  30  ab cd

In [322]:
df["문자길이"] = df["A"].str.len()
df

     A   B      C  문자길이
0  데이터  10  ab cd     3
1   기본  20  AB CD     2
2   퇴근  30  ab cd     2

In [323]:
df["C"] = df["C"].str.lower()
df

     A   B      C  문자길이
0  데이터  10  ab cd     3
1   기본  20  ab cd     2
2   퇴근  30  ab cd     2

In [324]:
df["C"] = df["C"].str.upper()
df

     A   B      C  문자길이
0  데이터  10  AB CD     3
1   기본  20  AB CD     2
2   퇴근  30  AB CD     2

In [325]:
df["C"] = df["C"].str.replace(" ", "")
df

     A   B     C  문자길이
0  데이터  10  ABCD     3
1   기본  20  ABCD     2
2   퇴근  30  ABCD     2

In [327]:
df["C_"] = df["C"].str[1:3]
df

     A   B     C  문자길이  C_
0  데이터  10  ABCD     3  BC
1   기본  20  ABCD     2  BC
2   퇴근  30  ABCD     2  BC

In [331]:
df["A"][1:3]

1    기본
2    퇴근
Name: A, dtype: object